#!/usr/bin/env bash

case "$1" in
    --help|-help|help)
        echo "haltroy's gamerun script"
        echo "Tries to run command with dedicated GPU, MangoHud, Gamemode and Strangle if possible."
        echo ""
        echo "Usage: gamerun [command]"
        echo "------------------------"
        echo "Set-up games for Steam with: gamerun %command%"
        echo ""
        echo ""
        echo "For configuring:"
        echo "System-wide configuration folder: /etc/gamerun/"
        echo "User configuration folder: $HOME/.config/gamerun/"
        echo "Every configuration option is handled by their own files respectively."
        echo "pre_launch: Script to run before launching (helpful for setting up gaming mode on certain compositors)"
        echo "post_launch: Script to run after launching"
        echo "disable_gpu: Disables GPU switching (prime-run and switcherooctl)"
        echo "disable_gamemode: Disables Gamemode"
        echo "disable_mangohud: Disables Mangohud (unless its enabled globally with MANGOHUD=1)"
        echo "disable_strangle: Disables libstrangle"
        echo "strangle_vars: Additional arguments to give to libstrangle (ex. \"60:40\" for 60 FPS on AC and 40 FPS on battery)."
        exit 0
        ;;
esac

PRE_GLOBAL="/etc/gamerun/pre_launch"
PRE_USER="$HOME/.config/gamerun/pre_launch"
POST_GLOBAL="/etc/gamerun/post_launch"
POST_USER="$HOME/.config/gamerun/post_launch"

# Run pre_launch scripts if they exist
[ -f "$PRE_GLOBAL" ] && bash "$PRE_GLOBAL"
[ -f "$PRE_USER" ] && bash "$PRE_USER"

command=""

# Strangle
if [ ! -f /etc/gamerun/disable_strangle ] && [ ! -f "$HOME/.config/gamerun/disable_strangle" ]; then
strangle_vars=""

# strangle arguments
if [ -f /etc/gamerun/strangle_vars ]; then
    strangle_vars=$(< /etc/gamerun/strangle_vars)
elif [ -f "$HOME/.config/gamerun/strangle_vars" ]; then
    strangle_vars=$(< "$HOME/.config/gamerun/strangle_vars")
fi
if type -P "strangle"  &>/dev/null; then
    command="$command strangle $strangle_vars"
fi
fi

# GPU
if [ ! -f /etc/gamerun/disable_gpu ] && [ ! -f "$HOME/.config/gamerun/disable_gpu" ]; then
if type -P "prime-run"  &>/dev/null; then
    command="$command prime-run"
elif type -P "switcherooctl"  &>/dev/null; then
    command="$command switcherooctl"
fi
fi

# mangohud
if [ ! -f /etc/gamerun/disable_mangohud ] && [ ! -f "$HOME/.config/gamerun/disable_mangohud" ]; then
if type -P "mangohud"  &>/dev/null; then
    command="$command mangohud"
fi
fi

# gamemode
if [ ! -f /etc/gamerun/disable_gamemode ] && [ ! -f "$HOME/.config/gamerun/disable_gamemode" ]; then
if type -P "gamemoderun"  &>/dev/null; then
    command="$command gamemoderun"
fi
fi
$command "$@"

# Run post_launch scripts if they exist
[ -f "$POST_GLOBAL" ] && bash "$POST_GLOBAL"
[ -f "$POST_USER" ] && bash "$POST_USER"