//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamerun.Shared.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Gamerun.Shared.Translations.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppIsRunning {
            get {
                return ResourceManager.GetString("AppIsRunning", resourceCulture);
            }
        }
        
        public static string ExceptionEndOfStream {
            get {
                return ResourceManager.GetString("ExceptionEndOfStream", resourceCulture);
            }
        }
        
        public static string AppNotFound {
            get {
                return ResourceManager.GetString("AppNotFound", resourceCulture);
            }
        }
        
        public static string ClientSocketException {
            get {
                return ResourceManager.GetString("ClientSocketException", resourceCulture);
            }
        }
        
        public static string ClientSecurityException {
            get {
                return ResourceManager.GetString("ClientSecurityException", resourceCulture);
            }
        }
        
        public static string ClientRunException {
            get {
                return ResourceManager.GetString("ClientRunException", resourceCulture);
            }
        }
        
        public static string DaemonInitizalized {
            get {
                return ResourceManager.GetString("DaemonInitizalized", resourceCulture);
            }
        }
        
        public static string DaemonRunningInScoket {
            get {
                return ResourceManager.GetString("DaemonRunningInScoket", resourceCulture);
            }
        }
        
        public static string DameonConnnectToSocketForShutdown {
            get {
                return ResourceManager.GetString("DameonConnnectToSocketForShutdown", resourceCulture);
            }
        }
        
        public static string DameonSocketEmpty {
            get {
                return ResourceManager.GetString("DameonSocketEmpty", resourceCulture);
            }
        }
        
        public static string DaemonSocketKilled {
            get {
                return ResourceManager.GetString("DaemonSocketKilled", resourceCulture);
            }
        }
        
        public static string DaemonStarted {
            get {
                return ResourceManager.GetString("DaemonStarted", resourceCulture);
            }
        }
        
        public static string DaemonRevertRequested {
            get {
                return ResourceManager.GetString("DaemonRevertRequested", resourceCulture);
            }
        }
        
        public static string DaemonClientConnected {
            get {
                return ResourceManager.GetString("DaemonClientConnected", resourceCulture);
            }
        }
        
        public static string ClientCannotFindApp {
            get {
                return ResourceManager.GetString("ClientCannotFindApp", resourceCulture);
            }
        }
        
        public static string ExceptionSocketNotFound {
            get {
                return ResourceManager.GetString("ExceptionSocketNotFound", resourceCulture);
            }
        }
        
        public static string ExceptionSocketNotUsable {
            get {
                return ResourceManager.GetString("ExceptionSocketNotUsable", resourceCulture);
            }
        }
        
        public static string DaemonShutdown {
            get {
                return ResourceManager.GetString("DaemonShutdown", resourceCulture);
            }
        }
        
        public static string DaemonAliveRequested {
            get {
                return ResourceManager.GetString("DaemonAliveRequested", resourceCulture);
            }
        }
        
        public static string DaemonBusyRequested {
            get {
                return ResourceManager.GetString("DaemonBusyRequested", resourceCulture);
            }
        }
        
        public static string DaemonBoostRequested {
            get {
                return ResourceManager.GetString("DaemonBoostRequested", resourceCulture);
            }
        }
        
        public static string DaemonReceivedGarbage {
            get {
                return ResourceManager.GetString("DaemonReceivedGarbage", resourceCulture);
            }
        }
        
        public static string DaemonReceivedNothing {
            get {
                return ResourceManager.GetString("DaemonReceivedNothing", resourceCulture);
            }
        }
        
        public static string DaemonCannotReplaceSocket {
            get {
                return ResourceManager.GetString("DaemonCannotReplaceSocket", resourceCulture);
            }
        }
    }
}
