//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamerun.Shared.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Gamerun.Shared.Translations.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppIsRunning {
            get {
                return ResourceManager.GetString("AppIsRunning", resourceCulture);
            }
        }
        
        public static string ExceptionEndOfStream {
            get {
                return ResourceManager.GetString("ExceptionEndOfStream", resourceCulture);
            }
        }
        
        public static string AppNotFound {
            get {
                return ResourceManager.GetString("AppNotFound", resourceCulture);
            }
        }
        
        public static string ClientSocketException {
            get {
                return ResourceManager.GetString("ClientSocketException", resourceCulture);
            }
        }
        
        public static string ClientSecurityException {
            get {
                return ResourceManager.GetString("ClientSecurityException", resourceCulture);
            }
        }
        
        public static string ClientRunException {
            get {
                return ResourceManager.GetString("ClientRunException", resourceCulture);
            }
        }
        
        public static string DaemonRunningInScoket {
            get {
                return ResourceManager.GetString("DaemonRunningInScoket", resourceCulture);
            }
        }
        
        public static string DameonConnnectToSocketForShutdown {
            get {
                return ResourceManager.GetString("DameonConnnectToSocketForShutdown", resourceCulture);
            }
        }
        
        public static string DameonSocketEmpty {
            get {
                return ResourceManager.GetString("DameonSocketEmpty", resourceCulture);
            }
        }
        
        public static string DaemonSocketKilled {
            get {
                return ResourceManager.GetString("DaemonSocketKilled", resourceCulture);
            }
        }
        
        public static string DaemonStarted {
            get {
                return ResourceManager.GetString("DaemonStarted", resourceCulture);
            }
        }
        
        public static string DaemonRevertRequested {
            get {
                return ResourceManager.GetString("DaemonRevertRequested", resourceCulture);
            }
        }
        
        public static string DaemonClientConnected {
            get {
                return ResourceManager.GetString("DaemonClientConnected", resourceCulture);
            }
        }
        
        public static string ClientCannotFindApp {
            get {
                return ResourceManager.GetString("ClientCannotFindApp", resourceCulture);
            }
        }
        
        public static string ExceptionSocketNotFound {
            get {
                return ResourceManager.GetString("ExceptionSocketNotFound", resourceCulture);
            }
        }
        
        public static string ExceptionSocketNotUsable {
            get {
                return ResourceManager.GetString("ExceptionSocketNotUsable", resourceCulture);
            }
        }
        
        public static string DaemonShutdown {
            get {
                return ResourceManager.GetString("DaemonShutdown", resourceCulture);
            }
        }
        
        public static string DaemonAliveRequested {
            get {
                return ResourceManager.GetString("DaemonAliveRequested", resourceCulture);
            }
        }
        
        public static string DaemonBusyRequested {
            get {
                return ResourceManager.GetString("DaemonBusyRequested", resourceCulture);
            }
        }
        
        public static string DaemonBoostRequested {
            get {
                return ResourceManager.GetString("DaemonBoostRequested", resourceCulture);
            }
        }
        
        public static string DaemonReceivedGarbage {
            get {
                return ResourceManager.GetString("DaemonReceivedGarbage", resourceCulture);
            }
        }
        
        public static string DaemonReceivedNothing {
            get {
                return ResourceManager.GetString("DaemonReceivedNothing", resourceCulture);
            }
        }
        
        public static string DaemonCannotReplaceSocket {
            get {
                return ResourceManager.GetString("DaemonCannotReplaceSocket", resourceCulture);
            }
        }
        
        public static string ClientHelpCommand {
            get {
                return ResourceManager.GetString("ClientHelpCommand", resourceCulture);
            }
        }
        
        public static string ClientHelpDesc {
            get {
                return ResourceManager.GetString("ClientHelpDesc", resourceCulture);
            }
        }
        
        public static string ClientHelpUsage {
            get {
                return ResourceManager.GetString("ClientHelpUsage", resourceCulture);
            }
        }
        
        public static string ClientHelpDaemon {
            get {
                return ResourceManager.GetString("ClientHelpDaemon", resourceCulture);
            }
        }
        
        public static string ClientHelpHelp {
            get {
                return ResourceManager.GetString("ClientHelpHelp", resourceCulture);
            }
        }
        
        public static string ClientHelpShutdown {
            get {
                return ResourceManager.GetString("ClientHelpShutdown", resourceCulture);
            }
        }
        
        public static string ClientHelpAlive {
            get {
                return ResourceManager.GetString("ClientHelpAlive", resourceCulture);
            }
        }
        
        public static string ClientHelpBusy {
            get {
                return ResourceManager.GetString("ClientHelpBusy", resourceCulture);
            }
        }
        
        public static string ClientHelpCMD {
            get {
                return ResourceManager.GetString("ClientHelpCMD", resourceCulture);
            }
        }
        
        public static string DaemonError {
            get {
                return ResourceManager.GetString("DaemonError", resourceCulture);
            }
        }
        
        public static string ConfigDefaultName {
            get {
                return ResourceManager.GetString("ConfigDefaultName", resourceCulture);
            }
        }
        
        public static string ConfigNewName {
            get {
                return ResourceManager.GetString("ConfigNewName", resourceCulture);
            }
        }
        
        public static string SidebarApps {
            get {
                return ResourceManager.GetString("SidebarApps", resourceCulture);
            }
        }
        
        public static string SidebarConfigs {
            get {
                return ResourceManager.GetString("SidebarConfigs", resourceCulture);
            }
        }
        
        public static string SidebarMangoHUD {
            get {
                return ResourceManager.GetString("SidebarMangoHUD", resourceCulture);
            }
        }
        
        public static string SidebarStrangle {
            get {
                return ResourceManager.GetString("SidebarStrangle", resourceCulture);
            }
        }
        
        public static string SidebarGamescope {
            get {
                return ResourceManager.GetString("SidebarGamescope", resourceCulture);
            }
        }
        
        public static string SidebarSettings {
            get {
                return ResourceManager.GetString("SidebarSettings", resourceCulture);
            }
        }
        
        public static string SidebarAbout {
            get {
                return ResourceManager.GetString("SidebarAbout", resourceCulture);
            }
        }
        
        public static string GamerunEditorTitle {
            get {
                return ResourceManager.GetString("GamerunEditorTitle", resourceCulture);
            }
        }
        
        public static string ExceptionConfigVersion1 {
            get {
                return ResourceManager.GetString("ExceptionConfigVersion1", resourceCulture);
            }
        }
        
        public static string ExceptionConfigVersion2 {
            get {
                return ResourceManager.GetString("ExceptionConfigVersion2", resourceCulture);
            }
        }
    }
}
