name: Build

on:
  #push:
  #  branches: ["main"]
  #pull_request:
  #  branches: ["main"]
  workflow_run:
    workflows: ['DevSkim']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build (CLI & Daemon)
        run: dotnet build --no-restore ./Gamerun/Gamerun.csproj
      - name: Build (Editor)
        run: dotnet build --no-restore ./Gamerun.Editor/Gamerun.Editor.csproj
